export { default as Registration } from './Registration'
export { default as Header } from './Header'
export { default as Activities } from './Activities'
export { default as Routines } from './Routines'
export { default as MyRoutines } from './MyRoutines'
